import { NextResponse } from 'next/server';
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { execSync } from 'node:child_process';
import { tmpdir } from 'node:os';
import { createHash } from 'node:crypto';
import { join } from 'node:path';
import * as YAML from 'yaml';
import { listAgents } from '@/lib/agents';

interface ScaffoldRequest {
  projectPath: string;
  projectName?: string;
  name: string;                  // kebab-case craft id (also dir name)
  displayName?: string;
  description: string;           // user's natural-language description
  agentId?: string;              // 'claude' | 'codex' | 'aider' | custom — defaults to first detected
}

const NAME_RE = /^[a-z][a-z0-9-]{1,40}$/;

// Tmux name prefix for craft-builder sessions; lives alongside Forge's "mw-" prefix
const SESSION_PREFIX = 'mw-craft-';

function buildScaffoldPrompt(displayName: string, description: string, name: string): string {
  return [
    `# Build the Forge Craft \`${name}\``,
    '',
    `**Display name**: ${displayName}`,
    '',
    'You are working inside the craft directory directly (cwd is `<project>/.forge/crafts/' + name + '/`).',
    'Use the `craft-builder` skill loaded in your environment for the full SDK reference and rules.',
    '',
    '## Files to write',
    '',
    '- `ui.tsx` — React component (default export). Import only from `@forge/craft`.',
    '- `server.ts` — optional. Only if you need server-side work. Import from `@forge/craft/server`.',
    '- Update `craft.yaml` if you need to change displayName / icon / showWhen.',
    '- Update `README.md` with a 1-paragraph description.',
    '- Append your work notes to `prompt.md` so future refines have context.',
    '',
    '## User\'s request',
    '',
    '```',
    description,
    '```',
    '',
    '## After you finish',
    '',
    'The craft will hot-reload in Forge as soon as the files exist. Tell the user to switch to the new tab in Forge to test it.',
    'Refer to the "Minimum viable example" in the `craft-builder` skill for the file shape and SDK use.',
    '',
    'Begin by reading `prompt.md` (this file) and the craft-builder skill, then write `ui.tsx`. End with `[FORGE_DONE]`.',
  ].join('\n');
}

function tmuxSessionName(projectPath: string, craftName: string): string {
  const projHash = createHash('md5').update(projectPath).digest('hex').slice(0, 6);
  return `${SESSION_PREFIX}${projHash}-${craftName}`;
}

export async function POST(req: Request) {
  const body = await req.json() as ScaffoldRequest;
  const { projectPath, projectName, name, displayName, description, agentId } = body;

  if (!projectPath || !name || !description) {
    return NextResponse.json({ error: 'projectPath, name, description required' }, { status: 400 });
  }
  if (!NAME_RE.test(name)) {
    return NextResponse.json({ error: 'name must be kebab-case: starts with letter, lowercase + digits + hyphens, 2-41 chars' }, { status: 400 });
  }

  const craftDir = join(projectPath, '.forge', 'crafts', name);
  if (existsSync(craftDir)) {
    return NextResponse.json({ error: `craft "${name}" already exists at ${craftDir} — pick a different name or delete it first` }, { status: 409 });
  }

  // Resolve agent
  const agents = listAgents();
  const enabled = agents.filter(a => a.enabled);
  if (enabled.length === 0) {
    return NextResponse.json({ error: 'no agents detected; install Claude Code, Codex, or Aider first' }, { status: 400 });
  }
  const agent = (agentId && enabled.find(a => a.id === agentId)) || enabled[0];

  // ── Scaffold files ────────────────────────────────────
  mkdirSync(craftDir, { recursive: true });
  mkdirSync(join(craftDir, 'data'), { recursive: true });

  const manifest = {
    name,
    displayName: displayName || `🛠 ${name}`,
    description: description.split('\n')[0].slice(0, 120),
    version: '0.1.0',
    ui: { tab: 'ui.tsx' },
  };
  writeFileSync(join(craftDir, 'craft.yaml'), YAML.stringify(manifest));

  // Stub UI so the tab appears immediately while the agent is still working
  writeFileSync(join(craftDir, 'ui.tsx'), `import { useProject } from '@forge/craft';

export default function Tab() {
  const { projectName } = useProject();
  return (
    <div className="flex-1 flex items-center justify-center p-8 text-xs text-[var(--text-secondary)]">
      <div className="text-center">
        <div className="text-2xl mb-2">🛠</div>
        <div>Craft <b className="text-[var(--text-primary)]">${name}</b> is being generated by ${agent.name || agent.id}.</div>
        <div className="mt-2 opacity-60">Once the agent writes ui.tsx, this tab will hot-reload.</div>
      </div>
    </div>
  );
}
`);

  const prompt = buildScaffoldPrompt(manifest.displayName, description, name);
  writeFileSync(join(craftDir, 'prompt.md'), prompt);

  writeFileSync(join(craftDir, 'README.md'), `# ${manifest.displayName}\n\n_Generation pending — agent ${agent.id} is working in tmux session ${tmuxSessionName(projectPath, name)}._\n`);

  // ── Launch tmux session + agent ───────────────────────
  const sessionName = tmuxSessionName(projectPath, name);
  try {
    // Kill any stale session with the same name (defensive)
    try { execSync(`tmux kill-session -t "${sessionName}" 2>/dev/null`, { timeout: 2000 }); } catch {}

    execSync(`tmux new-session -d -s "${sessionName}" -c "${craftDir}" -x 200 -y 50`, { timeout: 5000 });

    // Build CLI command — start the agent
    const cli = (agent as any).command || (agent as any).path || agent.id;
    let launchCmd = '';
    if (agent.id === 'claude') {
      launchCmd = `${cli} --dangerously-skip-permissions`;
    } else if (agent.id === 'codex') {
      launchCmd = `${cli}`;
    } else if (agent.id === 'aider') {
      launchCmd = `${cli} --yes`;
    } else {
      launchCmd = cli;
    }
    execSync(`tmux send-keys -t "${sessionName}" '${launchCmd}' Enter`, { timeout: 3000 });

    // Wait a moment for CLI to boot, then paste prompt + Enter
    setTimeout(() => {
      try {
        const buf = join(tmpdir(), `forge-craft-prompt-${Date.now()}.txt`);
        writeFileSync(buf, prompt);
        execSync(`tmux load-buffer -t "${sessionName}" "${buf}" && tmux paste-buffer -t "${sessionName}" && sleep 0.3 && tmux send-keys -t "${sessionName}" Enter`, { timeout: 5000 });
        try { require('node:fs').unlinkSync(buf); } catch {}
      } catch (e) {
        console.warn('[craft scaffold] failed to inject prompt', e);
      }
    }, 2500);
  } catch (e: any) {
    return NextResponse.json({ error: `failed to launch tmux session: ${e?.message || String(e)}` }, { status: 500 });
  }

  return NextResponse.json({
    ok: true,
    name,
    craftDir,
    sessionName,
    agent: { id: agent.id, displayName: agent.name || agent.id },
  });
}
